name: merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: merge
        run: gh pr merge --merge --auto "$PR_URL"
  squash:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'feature/teamA'
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: merge
        run: gh pr merge --squash --auto "$PR_URL"
